packages:
  - 'apps/*'
  - 'libs/*'
  - 'packages/*'

allowBuilds:
  '@google/genai': false
  '@swc/core': true
  better-sqlite3: true
  cpu-features: set this to true or false
  esbuild: true
  koffi: false
  protobufjs: false
  ssh2: set this to true or false
  unrs-resolver: true
